/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stm32f401xe.h>
#include <system_stm32f4xx.h>

#include <stdint.h>
#include <stdbool.h>

#include <mcalGPIO.h>
#include <mcalUsart.h>


uint8_t *outString =  (uint8_t *) "AT";

void USART2_IRQHandler(void);
void delay(uint16_t delay);

int main(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; // GPIOA :Bustakt aktivieren
	gpioSelectPinMode(GPIOA, PIN3, ALTFUNC); // PA2 :Modus = Alt. Funktion
	gpioSelectAltFunc(GPIOA, PIN3, AF7); // PA2 :AF7 = USART2 Rx
	gpioSelectPinMode(GPIOA, PIN2, ALTFUNC); // PA3 :Modus = Alt. Funktion
	gpioSelectAltFunc(GPIOA, PIN2, AF7); // PA3 :AF7 = USART2 Tx
	gpioSelectPinMode(GPIOA, PIN10, OUTPUT); // PA5 :GPIO-Output fuer LED

	// Hier werden sämtliche Parameter (Baudrate, Wortlaenge, Paritaet und
	// Anzahl der Stoppbits eingestellt.
	usartSelectUsart(USART2);
	usartEnableUsart(USART2);
	usartSetCommParams(USART2, 9600, NO_PARITY, LEN_8BIT, ONE_BIT);
	usartEnableIrq(USART2, USART_IRQ_RXNEIE);

	NVIC_EnableIRQ(USART2_IRQn);
	__enable_irq();
	/* Loop forever */
	for(;;){
		usartSendString(USART2, outString);
		delay(500);
	}
}


void delay(uint16_t delay)
{
	uint16_t i = 0;

	for (; delay > 0; --delay)
	{
		for (i = 0; i < 1245; ++i)
		{
			;
		}
	}
}

void USART2_IRQHandler(void)
{
	uint16_t received = 0;
	if (USART2->SR & USART_SR_RXNE)
	{
		received = USART2->DR & 0x01FF;
		if (received == 'a')
		{
			gpioSetPin(GPIOA, PIN10);
		}
		if (received == 'b')
		{
			gpioResetPin(GPIOA, PIN10);
		}
		if ((received >= 'A') && (received <= 'Z'))
		{
			usartSendByte(USART2, received);
		}
		if (received == 'c')
		{
			usartSendString(USART2, outString);
		}
	}


}
