/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <mcalSysTick.h>
#include <mcalUsart.h>
#include <mcalGPIO.h>

typedef enum{
	MAIN_INIT=0,
	MAIN_LOOP
}MAIN_MODE;




int main(void)
{
	MAIN_MODE mode = MAIN_INIT;
	for (;;) {
		switch (mode) {
		case MAIN_INIT:

			break;
		case MAIN_LOOP:
			break;

		}
	}
}
