/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#include <mcalSysTick.h>
#include <mcalUsart.h>
#include <mcalGPIO.h>

#include <bluetooth.h>
#include <RotaryPushButton.h>

#define BLUETOOTH_SETUP_TIME 500 //ms



typedef enum {
	MAIN_INIT=0,
	MAIN_LOOP
}MAIN_MODE;



bool timerTrigger;

volatile char usart2Buffer[USART2_BUFFER_SIZE];
volatile uint16_t usart2BufferIndex = 0;

int main(void) {

	/*
	 * Für Testzwecke
	 */
	gpioSelectPort(GPIOA);
	gpioSelectPinMode(GPIOA, PIN10, OUTPUT);

	uint32_t BluetoothTimer = 0UL; //Unsigned Long to set all bits to zero
	uint32_t BluetoothFetchTimer = 0UL;
	uint32_t Button=0UL;
	uint32_t ButtonLEDOff=0UL;
	uint32_t *timerList[] = { &BluetoothTimer, &BluetoothFetchTimer, &Button , &ButtonLEDOff};
	uint8_t arraySize = sizeof(timerList) / sizeof(timerList[0]);

	BluetoothModule_t HM17_1;

	MAIN_MODE mode = MAIN_INIT;

	bool buttonPressed = false;
	for (;;) {
		switch (mode) {
		// Initialize
		case MAIN_INIT:
			systickInit(SYSTICK_1MS);
			bool setupFinished = false;

			int8_t init1Status = -127;
			HM17_1.initStatus = -10;
			while (setupFinished == false) {
				if (timerTrigger == true) {
					systickUpdateTimerList((uint32_t*) timerList, arraySize);

				}
				if (isSystickExpired(BluetoothTimer)) {
					init1Status = bluetoothInit(&HM17_1, USART2, 9600);
					//gpioTogglePin(GPIOA, PIN10);
					systickSetTicktime(&BluetoothTimer, BLUETOOTH_SETUP_TIME);
				}
				if (isSystickExpired(BluetoothFetchTimer)) {
					bluetoothFetchBuffer(&HM17_1);

					systickSetTicktime(&BluetoothFetchTimer,
					BLUETOOTH_FETCH_TIME);
				}
				if(isSystickExpired(Button)){
					initRotaryPushButton();
					initRotaryPushButtonLED();
					systickSetTicktime(&Button, 20);
				}
				if (init1Status == 0) {
					setupFinished = true; // If all finished
				}
			}

			mode = MAIN_LOOP; // After setup switch to main loop
			gpioTogglePin(GPIOA, PIN10);

			break; //case MAIN_INIT

			// Loop forever
		case MAIN_LOOP:
			if (timerTrigger == true) {
				systickUpdateTimerList((uint32_t*) timerList, arraySize);

			}
			if (isSystickExpired(BluetoothTimer)) {

				if (buttonPressed == true) {
					bool reply;
					int16_t status;
					status = bluetoothGetStatus(&HM17_1, &reply);
					if (status == 0) { // We are OK
						buttonPressed = false;
						systickSetTicktime(&ButtonLEDOff, 2000);
						if(reply == true){
							setRotaryColor(LED_GREEN);

						}else{
							setRotaryColor(LED_RED);
						}
					} else if (status > 0) {
						systickSetTicktime(&ButtonLEDOff, 2000);
						buttonPressed = false;
						setRotaryColor(LED_RED);
					}
				}

				systickSetTicktime(&BluetoothTimer, 200);
			}
			if (isSystickExpired(BluetoothFetchTimer)) {
				bluetoothFetchBuffer(&HM17_1);

				systickSetTicktime(&BluetoothFetchTimer,
				BLUETOOTH_FETCH_TIME);
			}
			if (isSystickExpired(Button)) {

				if (getRotaryPushButton() == true) {
					buttonPressed = true;
					setRotaryColor(LED_BLUE);
				}

				systickSetTicktime(&Button, 20);
			}
			if (isSystickExpired(ButtonLEDOff)) {

				setRotaryColor(LED_BLACK);

			}

			break; // case MAIN_LOOP

		}
	}
}
