/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#include <stm32f4xx.h>

#include <mcalSysTick.h>
#include <mcalGPIO.h>
#include <mcalSPI.h>
#include <mcalI2C.h>
#include <mcalSysTick.h>
#include <RotaryPushButton.h>
#include <BALO.h>
#include <ST7735.h>
#include <MPU6050.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

bool timerTrigger;

int main(void) // ToDo: Visualisierung über Oszilloskop
{
	initRotaryPushButton();
	initRotaryPushButtonLED();
	setRotaryColor(LED_BLACK);

	/* I²C initialisieren */
	i2cActivate();

	MPU6050_t MPU1;
	int8_t testVal = MPU_init(&MPU1, I2C1, i2cAddr_MPU6050, 2, 3, MPU6050_LPBW_5, RESTART);
	float anglefactor = 180/_pi;

	if (testVal >= 0) {
		setRotaryColor(LED_GREEN);
		/* Erfolgreiche Kommunikation */
		for (;;) {
			testVal = 	MPU_get_angle_from_acceleration(&MPU1);
			testVal += 	MPU_get_temperature(&MPU1);
			testVal += 	MPU_get_gyro(&MPU1);
			// In Grad umrechnen, da besser greifbar
			float alpha	= MPU1.alpha_beta[0]*anglefactor;
			float beta	= MPU1.alpha_beta[1]*anglefactor;
			if (testVal != 0) {
				setRotaryColor(LED_RED);
			}
		}
	}
	else {
		setRotaryColor(LED_RED);
		/* Fehlgeschlagene Kommunikation */
		for (;;) {

		}
	}
}
